### ISSUE TITLE
About BRDFRead

### ISSUE THREAD

**Issue by WANGYINGYU** [hiroaki-santo/deep-photometric-stereo-network#1]
Hello,
I am very interested in this project，but I got an error when compiling the project merl_brdf_database.I compiled on Mac os. There was no error in cmake, but the following error occurred during make.

> Charlies-MacBook-Pro:merl_brdf_database charlie$ make
Scanning dependencies of target BRDFRead
[ 50%] Building CXX object CMakeFiles/BRDFRead.dir/BRDFRead.cpp.o
/Users/charlie/Documents/dpsn/deep-photometric-stereo-network/merl_brdf_database/BRDFRead.cpp:36:9: warning:
      'M_PI' macro redefined [-Wmacro-redefined]
#define M_PI    3.1415926535897932384626433832795
        ^
/usr/include/math.h:703:9: note: previous definition is here
#define M_PI        3.14159265358979323846264338327950288   /* pi             */
        ^
1 warning generated.
[100%] Linking CXX shared library BRDFRead.dylib
Undefined symbols for architecture x86_64:
  "boost::numpy::initialize(bool)", referenced from:
      init_module_BRDFRead() in BRDFRead.cpp.o
  "boost::numpy::zeros(boost::python::tuple const&, boost::numpy::dtype const&)", referenced from:
      read_brdfpy(char const*) in BRDFRead.cpp.o
  "boost::numpy::dtype boost::numpy::detail::get_float_dtype<64>()", referenced from:
      read_brdfpy(char const*) in BRDFRead.cpp.o
  "boost::python::detail::init_module(PyModuleDef&, void (*)())", referenced from:
      _PyInit_BRDFRead in BRDFRead.cpp.o
  "boost::python::converter::object_manager_traits<boost::numpy::ndarray>::get_pytype()", referenced from:
      boost::python::detail::converter_target_type<boost::python::to_python_value<boost::numpy::ndarray const&> >::get_pytype() in BRDFRead.cpp.o
      boost::python::detail::caller_arity<5u>::impl<boost::python::tuple (*)(boost::numpy::ndarray, double, double, double, double), boost::python::default_call_policies, boost::mpl::vector6<boost::python::tuple, boost::numpy::ndarray, double, double, double, double> >::operator()(_object*, _object*) in BRDFRead.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [BRDFRead.dylib] Error 1
make[1]: *** [CMakeFiles/BRDFRead.dir/all] Error 2
make: *** [all] Error 2

I can't solve this problem. Do you have any suggestions?

**Comment by hiroaki-santo** [comment]
Hi,
Thank you for your interest. First of all, I recommend using my `Dockerfile` if you can. I'm sure that it provides the same environment as ours. Our cmake configuration is tested only in Ubuntu environment, and so I'm not sure it works in other environments.

I'm not sure but your error occurs in the linker, and so you need to check the environment (PATH or something) of `Boost:numpy`.
