### ISSUE TITLE
About rendered image

### ISSUE THREAD

**Issue by hasayake007** [hiroaki-santo/deep-photometric-stereo-network#4]
Hello, I found a mistake about the dataset.
Yesterday, I used the Dockerfile you provided to produce the dataset. But I found some materials image is very black and not normal, for example, the alumina-oxide in fig 1.
![0](https://user-images.githubusercontent.com/37137680/50037105-1d8e7a00-0049-11e9-9e78-9383f80cdfef.png)
I opened this image in Matlab and I found its intensity is in [0,255]. Because the rendered image is uint16, I multiplied the rendered image by 255, it looks normal as follows：
![2345 20181215091739](https://user-images.githubusercontent.com/37137680/50037250-52e79780-004a-11e9-9a23-2a59d97885b2.jpg)
However，It's not right for every material. The rendered image of blue-fabric is 
![1](https://user-images.githubusercontent.com/37137680/50037337-081a4f80-004b-11e9-9d67-e84e5f664e25.png)
and  multiplied the rendered image by 255 is 
![2345 20181215092449](https://user-images.githubusercontent.com/37137680/50037366-4fa0db80-004b-11e9-885b-91a07301e33b.jpg)
it seems to overflow.
what is wrong?
Could you please provide the original dataset if it's convenient?
I am looking forward to your reply! Thank you very much

**Comment by hiroaki-santo** [comment]
Hi, thank you for asking.
The rendered images are not normalized for each images, but normalized by the maximum intensity of whole #lights images. We need to keep the consistency of intensities in #lights images for photometric stereo.
So could you check for whole #lights images?
